### ISSUE TITLE
confused by return value of sd.GetCapability(twain.ICAP_BITDEPTH)

### ISSUE THREAD

**Issue by kallyshall** [denisenkom/pytwain#17]
I am trying to get the range or the possible value of bpp by using this sd.GetCapability(twain.ICAP_BITDEPTH) and get the return value (4, (0, 0, [24]))

According to the document, 4 means type(uint16), but I am confused by the tuple followed.
For now, I have tried several values to set the bpp, only 0 and 1(also  the default value)works.

need help :3

**Comment by songjingwei** [comment]
You can see this:  https://github.com/denisenkom/pytwain/issues/15#issuecomment-306071455
