### ISSUE TITLE
Error when using twain.SourceManager(0)

### ISSUE THREAD

**Issue by jhnwllr** [denisenkom/pytwain#2]
Hello, 

When using pytwain on windows 7 (32 bit), python 2.7 (32 bit), I get the following error. 

>> import twain
>> sm = twain.SourceManager(0)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\twain.py", line 2036
    raise excSMOpenFailed("[%s], return code %d" % (dsm_na
twain.excSMOpenFailed: [twain_32.dll], return code 1

I have been able to get pytwain to run this command without error on a different computer, but I also get this error on multiple different computers. 

Any idea?

**Comment by funsim** [comment]
You are missing the ``twain_32.dll`` library.

Try installing the twacker 32 package from http://www.twain.org/scannerdriverdevelopers/specification-and-tools.html
