### ISSUE TITLE
errors in lowlevel.py

### ISSUE THREAD

**Issue by abubelinha** [denisenkom/pytwain#26]
Hello

I am trying to run examples in demo folder, and my Python 3.4 (Windows 7) reports several errors:
https://github.com/denisenkom/pytwain/blob/master/demo/lowlevel.py

Line 48:  `sm = twain.SourceManager(0L)`
Error: _invalid syntax_ (referred to the text inside parenthesis)

Line 58: `print ProductName` 
Error: _missing parenthesis_

The last one is easy to solve. 
But for the first one I don't really know what would be the correct value.
I changed _0L_ by _0_, but now I get this error:

```
Traceback (most recent call last):
  File "C:\Dropbox\python\pytwain\pytwain_lowlevel.py", line 48, in <module>
    sm = twain.SourceManager(0) # CHANGED: 0L raises "invalid syntax" error 
  File "C:\python-3.4.4\lib\site-packages\twain.py", line 2036, in __init__
    raise excSMOpenFailed("[%s], return code %d" % (dsm_name, rv))
twain.excSMOpenFailed: [twain_32.dll], return code 1
```

**Comment by denisenkom** [comment]
try changing 0L to 0

**Comment by denisenkom** [comment]
Low level API is not supported anymore
