### ISSUE TITLE
Want to use pytwain with a GPL-V3 licensed software

### ISSUE THREAD

**Issue by yncat** [denisenkom/pytwain#27]
Currently, this module is licensed under GPL v2.0. We'd like to use the library  in our software, but our code is licensed under GPL v3. There's a conflict between the two GPL versions, meaning that GPL-v3 licensed code cannot import / use v2 licensed modules legally. Could you please consider adding GPL-v3 license for this library?

**Comment by denisenkom** [comment]
This project was based on http://twainmodule.sourceforge.net/, that is probably where GPL v2.0 is coming from.  So I am not sure that I can change it.

**Comment by yncat** [comment]
Thanks for your comment. Reading the GPL specifications, I don't think you can change it. But I appreciate your clarification!
