### ISSUE TITLE
import thinter error in demo\scan.py, it should be uppercase Thinter

### ISSUE THREAD

**Issue by zemug** [denisenkom/pytwain#3]
import thinter error in demo\scan.py, it should be uppercase Thinter
and no messagebox in tkinter package

``` diff
 import twain
 import sys
-from tkinter import *
-from tkinter import messagebox
+from Tkinter import *
+from tkMessageBox import showerror
 import traceback

 root = Tk()
 root.title('scan.py')

 if len(sys.argv) != 2:
-    messagebox.showerror("Error", "Usage: python scan.py <filename>")
+    showerror("Error", "Usage: python scan.py <filename>")
     exit(1)
```

**Comment by denisenkom** [comment]
IFAIR demo/scan.py is Python 3 compatible, can you check it on Python 3?

**Comment by zemug** [comment]
> IFAIR demo/scan.py is Python 3 compatible, can you check it on Python 3?

Yes, demo works on Python 3. 
It seems not a problem.  The core code work with python 2.7.

**Comment by denisenkom** [comment]
Thanks
