### ISSUE TITLE
About Scanner setup UI

### ISSUE THREAD

**Issue by GrabGrab** [denisenkom/pytwain#30]
I use TWAIN twacker to set the scanner function through the setup function, but I don't see it in pytwain

Is there any way to call? 

![image](https://user-images.githubusercontent.com/24184095/160289451-96fa7f2c-cdb5-4fdc-bd1a-28c1bb96758b.png)

**Comment by denisenkom** [comment]
It is not clear what this issue is about, can you provide more details?
