### ISSUE TITLE
scanner user interface

### ISSUE THREAD

**Issue by Dhruv00710** [denisenkom/pytwain#35]
When i show scanner user interface in simple_wx.py file and its show but when i click on scanner user interface close button its not close .

**Comment by denisenkom** [comment]
I wasn't able to reproduce this issue, can you try on the latest version? Can you provide more detailed repro instructions?

**Comment by Dhruv00710** [comment]
sir i try latest version but not solved. and i make OMR software. in this software i used this library and i scan and save multiple file . after i used bellowed code 
import twain
import uuid
sm = twain.SourceManager(0)
ss = sm.OpenSource()
ss.RequestAcquire(1,1)
while True:
    try:
        rv = ss.XferImageNatively()
        if rv:
            (handle, count) = rv
            twain.DIBToBMFile(handle, '{}.bmp'.format(uuid.uuid4()))
        else:
            break
    except:
          print("Error") 
          break
 in this code ss.RequestAcquire(0,0) its run perfectly when ss.RequestAcquire(1,1) its get error like
Exception ignored in: <function SourceManager.__del__ at 0x02F41898>
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\twain.py", line 2066, in __del__
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\twain.py", line 2073, in close
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311-32\Lib\_weakrefset.py", line 105, in pop
KeyError: 'pop from empty WeakSet'

**Comment by denisenkom** [comment]
Interesting problem, I found that it works if you call `request_acquire` inside the loop together with `hide_ui` like this:
```python
sm = twain.SourceManager(root)
ss = sm.open_source()
while True:
    ss.request_acquire(show_ui=False, modal_ui=False)
    rv = ss.xfer_image_natively()
    if rv:
        (handle, count) = rv
        print(f"number of images remaining: {count}")
        twain.dib_to_bm_file(handle, '{}.bmp'.format(uuid.uuid4()))
    else:
        break
    ss.hide_ui()
```
My theory is that the lack of event loop message pumping is causing this problem.  I will look more into that.

**Comment by Dhruv00710** [comment]
res. sir 
i use below code
sm = twain.SourceManager(root)
ss = sm.open_source()
while True:
    ss.request_acquire(show_ui=False, modal_ui=False)
    rv = ss.xfer_image_natively()
    if rv:
        (handle, count) = rv
        print(f"number of images remaining: {count}")
        twain.dib_to_bm_file(handle, '{}.bmp'.format(uuid.uuid4()))
    else:
        break
    ss.hide_ui()
but its error like
 File "e:\GKIQ-2023\Student Entry\pytwain-master\demo\1.py", line 6, in <module>
    ss.request_acquire(show_ui=False, modal_ui=False)
    ^^^^^^^^^^^^^^^^^^
AttributeError: '_Source' object has no attribute 'request_acquire'. Did you mean: 'RequestAcquire'?
Exception ignored in: <function SourceManager.__del__ at 0x01251848>
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\twain.py", line 2066, in __del__
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\twain.py", line 2073, in close
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311-32\Lib\_weakrefset.py", line 105, in pop
KeyError: 'pop from empty WeakSet'

**Comment by denisenkom** [comment]
Upgrade to latest version 2.1.0 and try again.

**Comment by Dhruv00710** [comment]
Sir I have typed the code as per the example you provided. And when I put a multiple document in the ADF, only 1 image is saved in the path we have given.

The second is that when all the documents in the ADF are scanned and the message comes that you still want to scan the document, then if we say yes, it will scan and if we say no, it will give us the following error.
File "e:\GKIQ-2023\Student Entry\pytwain-master\1.py", line 14, in <module>
    ss.request_acquire(show_ui=False, modal_ui=False)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\twain\__init__.py", line 560, in request_acquire
    self._enable(show_ui, modal_ui, self._sm._hwnd)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\twain\__init__.py", line 403, in _enable
    self._call(DG_CONTROL, DAT_USERINTERFACE, MSG_ENABLEDS, ct.byref(ui))
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\twain\__init__.py", line 175, in _call
    return self._sm._call(self._id, dg, dat, msg, buf, expected_returns)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\twain\__init__.py", line 968, in _call
    raise exc
twain.exceptions.excTWCC_BUMMER

Sir please can you give me one such example. which has a checkbox and two buttons. 
-> The function of the checkbox is to open the scanner window. 
-> There is a button named Select Scanner which allows us to select the scanner. And if we don't select scanner then it will automatically select default scanner.
 -> There is a button named Scan which allows us to scan multiple documents and save the document in the given path.

Sir humble request to you please solve my query because on dated 22-10-2023 we organize exam. And we check all OMR sheet using OMR checking software. In this software I use pytwain library.

**Comment by denisenkom** [comment]
I need more details, can you send me debug logging output? Set logging level to debug: `logging.basicConfig(level=logging.DEBUG)` and then send me logging output of your program.

**Comment by Dhruv00710** [comment]
Thanks sir but my Query "Sir I have typed the code as per the example you provided. And when I put a multiple document in the ADF, only 1 image is saved in the path we have given.

The second is that when all the documents in the ADF are scanned and the message comes that you still want to scan the document, then if we say yes, it will scan and if we say no, it will give us the following error." 
is solved. but when open select scanner menu and click on cancel button its get error like
File "e:\GKIQ-2023\Student Entry\pytwain-master\1.py", line 13, in <module>
    with sm.open_source() as ss:  # this posts a modeless dialog...
TypeError: 'NoneType' object does not support the context manager protocol



my second Query is that can you give me more example like 

which has a checkbox and two buttons.
-> The function of the checkbox is to open the scanner window (show scanner user interface).
-> There is a button named Select Scanner which allows us to select the scanner. And if we don't select scanner then it will automatically select default scanner.
-> There is a button named Scan which allows us to scan multiple documents with scanner window and save the document in the given path.

**Comment by denisenkom** [comment]
> but when open select scanner menu and click on cancel button its get error like
File "e:\GKIQ-2023\Student Entry\pytwain-master\1.py", line 13, in
with sm.open_source() as ss: # this posts a modeless dialog...
TypeError: 'NoneType' object does not support the context manager protocol

You should check return value of `open_source()` before using it in `with` statement. If `None` is returned then this means user cancelled source selection dialog.  See documentation for `open_source` function: https://pytwain.readthedocs.io/en/latest/twain.html#twain.SourceManager.open_source

> my second Query is that can you give me more example like...

I don't have such specific example. Take a look at examples in demo folder: https://github.com/denisenkom/pytwain/tree/master/demo, you may find something like what you want.

**Comment by Dhruv00710** [comment]
def test_multiple_images_scan(root_window):
    logging.basicConfig(level=logging.DEBUG)
    with twain.SourceManager(root_window) as sm:
        with sm.open_source() as ss:
            for _ in range(2):
                ss.request_acquire(show_ui=False, modal_ui=False)
                rv = ss.xfer_image_natively()
                if rv:
                    (handle, count) = rv
                    print(f"number of images remaining: {count}")
                    twain.dib_to_bm_file(handle, 'testscans/{}.bmp'.format(uuid.uuid4()))
                else:
                    break
                ss.hide_ui()
sir using above code when  ss.request_acquire(show_ui=True, modal_ui=False) or ss.request_acquire(show_ui=True, modal_ui=True) in both situation. its give error like
INFO:__main__:Creating source manager
INFO:lowlevel:attempting to load dll: C:\Windows\twain_32.dll
INFO:lowlevel:DSM initialized
INFO:__main__:Opening source
INFO:lowlevel:starting source selection dialog
INFO:lowlevel:user selected source with id 827
INFO:lowlevel:opening data source with id 827
INFO:__main__:Request acquire
INFO:lowlevel:starting scan
INFO:__main__:Transferring image
INFO:lowlevel:closing data source with id 827
ERROR:__main__:Error: module 'twain.exceptions' has no attribute 'DSTransferCancelled'
