### ISSUE TITLE
No module named pytwain

### ISSUE THREAD

**Issue by Koruyo** [denisenkom/pytwain#36]
Hello everybody!
I tried it on windows i tried it on mac os... no idea what the problem is...

Currently Python Version 3.11.5 - also tried it with 3.11.2, and python 32bit 3.11.5 and python 64bit 3.11.5 on windows

Terminal: pyenv versions
  system
* 3.11.5 (set by /Users/user/.pyenv/version)

Terminal: pip install pytwain

Terminal: pip list
pip        23.2.1
pytwain    2.1.0

Terminal: pip show pytwain
Name: pytwain
Version: 2.1.0
Summary: TWAIN API for accessing scanners, cameras, etc on Windows
Home-page: https://github.com/denisenkom/pytwain
Author: Mikhail Denisenko
Author-email: denisenkom@gmail.com
License: 
Location: /Users/user/.pyenv/versions/3.11.5/lib/python3.11/site-packages
Requires: 
Required-by: 

Terminal: python scanner_test.py
Traceback (most recent call last):
  File "/Users/user/Desktop/scanner.py", line 1, in <module>
    import pytwain
ModuleNotFoundError: No module named 'pytwain'

edit:
Now also tried it with downloading the https://pypi.org/project/pytwain/#files tar.gz and running setup.py install...

python setup.py install
running install
/Users/user/.pyenv/versions/3.11.5/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/Users/user/.pyenv/versions/3.11.5/lib/python3.11/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing src/pytwain.egg-info/PKG-INFO
writing dependency_links to src/pytwain.egg-info/dependency_links.txt
writing top-level names to src/pytwain.egg-info/top_level.txt
reading manifest file 'src/pytwain.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'COPYING.txt'
writing manifest file 'src/pytwain.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-13.6-arm64/egg
running install_lib
running build_py
creating build/bdist.macosx-13.6-arm64/egg
creating build/bdist.macosx-13.6-arm64/egg/twain
copying build/lib/twain/__init__.py -> build/bdist.macosx-13.6-arm64/egg/twain
copying build/lib/twain/utils.py -> build/bdist.macosx-13.6-arm64/egg/twain
copying build/lib/twain/exceptions.py -> build/bdist.macosx-13.6-arm64/egg/twain
creating build/bdist.macosx-13.6-arm64/egg/twain/lowlevel
copying build/lib/twain/lowlevel/constants.py -> build/bdist.macosx-13.6-arm64/egg/twain/lowlevel
copying build/lib/twain/lowlevel/__init__.py -> build/bdist.macosx-13.6-arm64/egg/twain/lowlevel
copying build/lib/twain/lowlevel/structs.py -> build/bdist.macosx-13.6-arm64/egg/twain/lowlevel
copying build/lib/twain/windows.py -> build/bdist.macosx-13.6-arm64/egg/twain
byte-compiling build/bdist.macosx-13.6-arm64/egg/twain/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.macosx-13.6-arm64/egg/twain/utils.py to utils.cpython-311.pyc
byte-compiling build/bdist.macosx-13.6-arm64/egg/twain/exceptions.py to exceptions.cpython-311.pyc
byte-compiling build/bdist.macosx-13.6-arm64/egg/twain/lowlevel/constants.py to constants.cpython-311.pyc
byte-compiling build/bdist.macosx-13.6-arm64/egg/twain/lowlevel/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.macosx-13.6-arm64/egg/twain/lowlevel/structs.py to structs.cpython-311.pyc
byte-compiling build/bdist.macosx-13.6-arm64/egg/twain/windows.py to windows.cpython-311.pyc
creating build/bdist.macosx-13.6-arm64/egg/EGG-INFO
copying src/pytwain.egg-info/PKG-INFO -> build/bdist.macosx-13.6-arm64/egg/EGG-INFO
copying src/pytwain.egg-info/SOURCES.txt -> build/bdist.macosx-13.6-arm64/egg/EGG-INFO
copying src/pytwain.egg-info/dependency_links.txt -> build/bdist.macosx-13.6-arm64/egg/EGG-INFO
copying src/pytwain.egg-info/top_level.txt -> build/bdist.macosx-13.6-arm64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/pytwain-2.1.0-py3.11.egg' and adding 'build/bdist.macosx-13.6-arm64/egg' to it
removing 'build/bdist.macosx-13.6-arm64/egg' (and everything under it)
Processing pytwain-2.1.0-py3.11.egg
Removing /Users/user/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pytwain-2.1.0-py3.11.egg
Copying pytwain-2.1.0-py3.11.egg to /Users/user/.pyenv/versions/3.11.5/lib/python3.11/site-packages
pytwain 2.1.0 is already the active version in easy-install.pth

Installed /Users/user/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pytwain-2.1.0-py3.11.egg
Processing dependencies for pytwain==2.1.0
Finished processing dependencies for pytwain==2.1.0

still
ModuleNotFoundError: No module named 'pytwain'

edit: just in case i also tested
import pytwain
import twain
import twain as pytwain
import pytwain as twain
all result in
ModuleNotFoundError: No module named '...'

**Comment by denisenkom** [comment]
You need to write `import twain` instead of `import pytwain`
