### ISSUE TITLE
Mention that you depend on TWAINDSM

### ISSUE THREAD

**Issue by MerlijnWajer** [denisenkom/pytwain#4]
The software doesn't mention it requires the TWAINDSM .dll files to be available. It would be useful to mention this.

**Comment by denisenkom** [comment]
It shouldn't be required.  When there is no twaindsm.dll in the system it will try to load twain_32.dll, which comes with windows itself.
Was twain_32.dll missing on your system?  Can you provide more details?

**Comment by MerlijnWajer** [comment]
I was using a 64 bit system, where only 32 bit TWAIN drivers were provided. Sorry for not mentioning this before, and sorry for the delay in answering. I need to boot my Windows machine if you want more information.

**Comment by MerlijnWajer** [comment]
I was/am also using a 64 bit python install, so I wanted to use 64 bit TWAIN. The TWAINDSM for 64 bit seemed to be missing. In the end I gave up because my scanner had only 32 bit TWAIN support on my 64 bit Windows. (canon...)

Anyway - the issue is likely that 64 bit twaindsm files are missing?

**Comment by denisenkom** [comment]
If your scanner support 32 bit only you would have to use 32 Python and 32 bit twain dll.

AFAIK Windows is shipped with both 32 and 64 bit twain dlls, so TWAINDSM shouldn't be required, I may be wrong on that one

**Comment by MerlijnWajer** [comment]
> If your scanner support 32 bit only you would have to use 32 Python and 32 bit twain dll.

Yes, I realised that before I filed this bug. I just recall still having to get TWAINDSM for my 64 bit system, with 64 bit python. After I got the .dll, pytwain started to work and told me (correctly) no 64 bit scanners were found.

**Comment by MerlijnWajer** [comment]
Feel free to close the issue -- as it is a bit vague, I guess. Next time I have to work with Windows (in a few months), and I'll let you know if the issue persists or not.

**Comment by denisenkom** [comment]
I added comment to readme file, thanks!
