### ISSUE TITLE
Bresser dialog

### ISSUE THREAD

**Issue by ji-ze** [denisenkom/pytwain#43]
I using [BRESSER MikroCamII 9MP](https://www.bresser.de/en/Microscopes-Magnifiers/Accessories/BRESSER-MikroCamII-9MP-4K-1-Microscope-Camera.html?mtm_campaign=Doofinder&mtm_kwd=5914090&mtm_source=English&mtm_medium=OnSite&mtm_cid=GreatBritain&mtm_group=SiteSearch) which uses the pytwain library. If I run the following code:

```
import twain
import tkinter
import logging

def after(i, num):

    print(i._handle, num)
    twain.windows.dib_to_bm_file(i, 'Test001.bmp')
    print(i, num)


logging.basicConfig(level=logging.DEBUG)
root = tkinter.Tk()
root.title('scan.py')
with twain.SourceManager(root) as sm:
    # this will show UI to allow user to select source
    src = sm.open_source()
    #print(src.image_info())
    #print(f"matrix: {src}")
    if src:
        src.acquire_natively(after, show_ui=True)
    else:
        print("User clicked cancel")
```

This dialog is opened:
![image](https://github.com/denisenkom/pytwain/assets/44098973/f9219ad1-92b8-4e53-aec4-19516706a4ab)
![image](https://github.com/denisenkom/pytwain/assets/44098973/fa7c81ef-f433-4d7b-9381-2d8356676614)

After clicking to "Snap", the terminal writes:

```
INFO:twain:Calling DAT_EVENT/MSG_PROCESSEVENT
DEBUG:twain:handling event result 4
INFO:twain:transfer is ready
INFO:twain:got MSG_XFERREADY message
INFO:twain:Calling DAT_IMAGEINFO/MSG_GET
INFO:twain:Calling DAT_IMAGENATIVEXFER
INFO:twain:Calling DAT_PENDINGXFERS/MSG_ENDXFER
INFO:twain:Calling DAT_USERINTERFACE/MSG_DISABLEDS
2609114120408 0
INFO:twain:closing data source with id 1
INFO:twain:Calling DAT_IDENTITY/MSG_CLOSEDS
INFO:twain:Calling DAT_PARENT/MSG_CLOSEDSM
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\GitHub\Sample_scaner\Snaper\twain_scan_test.py", line 21, in <module>
    src.acquire_natively(after, show_ui=True)
  File "C:\ProgramData\miniconda3\Lib\site-packages\twain\__init__.py", line 933, in acquire_natively
    self._acquire(xfer_ready_callback=xfer_ready_callback, show_ui=show_ui, modal=modal)
  File "C:\ProgramData\miniconda3\Lib\site-packages\twain\__init__.py", line 643, in _acquire
    self._modal_loop(event_callback_lolevel)
  File "C:\ProgramData\miniconda3\Lib\site-packages\twain\__init__.py", line 611, in _modal_loop
    event_callback(event)
  File "C:\ProgramData\miniconda3\Lib\site-packages\twain\__init__.py", line 637, in event_callback_lolevel
    more = xfer_ready_callback()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\site-packages\twain\__init__.py", line 927, in xfer_ready_callback
    after(_Image(handle=handle, free=self._free, lock=self._lock, unlock=self._unlock), more)
  File "C:\Users\Administrator\Documents\GitHub\Sample_scaner\Snaper\twain_scan_test.py", line 8, in after
    twain.windows.dib_to_bm_file(i, 'Test001.bmp')
  File "C:\ProgramData\miniconda3\Lib\site-packages\twain\windows.py", line 121, in dib_to_bm_file
    return _dib_write(handle, path, GlobalLock, GlobalUnlock)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\site-packages\twain\windows.py", line 72, in _dib_write
    ptr = lock(handle)
          ^^^^^^^^^^^^
ctypes.ArgumentError: argument 1: TypeError: wrong type
```

I use the last version from GitHub with commits: Fix missing _lock and _unlock method on the _Image class
, Fix missing _free method on the _Image class. The last official release 2.2.2 has bug on the _Image class.

**Comment by ji-ze** [comment]
If I open the __init__.py, an editor writes:
![image](https://github.com/denisenkom/pytwain/assets/44098973/ef2bdcdd-4187-4a2d-b749-83c0682e165c)

**Comment by ji-ze** [comment]
There is a problem
![image](https://github.com/denisenkom/pytwain/assets/44098973/1a7817a1-e21b-4e45-962b-742c11082b3a)

**Comment by denisenkom** [comment]
Hi Jiří,
Look like you are actually using old version instead of using latest version from Github.  I see that from stack trace which indicates that line 72 in windows.py contains call to lock function, while on latest version this line is different.  Make sure you are using latest version.

**Comment by denisenkom** [comment]
I also released version 2.3.0 with latest code, so you can install it instead.

**Comment by ji-ze** [comment]
Hi denisenkom,
Thank you for getting back to me. I have installed the 2.3.0 version:
![image](https://github.com/denisenkom/pytwain/assets/44098973/add93f19-79be-4d19-8ccf-d4d464371771),
but the saving images don't work. I get a different error in windows.py. I checked to have the same windows.py file as there is on this repository.
![image](https://github.com/denisenkom/pytwain/assets/44098973/be5589fe-9716-40c3-8bf6-3c5e990dc16c)

**Comment by ji-ze** [comment]
handle is twain._Image object in my code:
![image](https://github.com/denisenkom/pytwain/assets/44098973/b64457f0-2ff1-4ab4-b314-223c64e381b1)
![image](https://github.com/denisenkom/pytwain/assets/44098973/8664567a-44f0-43d5-bd31-602e5c34ab84)

**Comment by ji-ze** [comment]
If I use the code from this repository:
'''
from io import BytesIO
import twain
import tkinter
from tkinter import ttk
import logging
import PIL.ImageTk
import PIL.Image

scanned_image = None


def scan():
    global scanned_image
    with twain.SourceManager(root) as sm:
        # this will show UI to allow user to select source
        src = sm.open_source()
        if src:
            src.request_acquire(show_ui=False, modal_ui=False)
            (handle, remaining_count) = src.xfer_image_natively()
            bmp_bytes = twain.dib_to_bm_file(handle)
            img = PIL.Image.open(BytesIO(bmp_bytes), formats=["bmp"])
            width, height = img.size
            factor = 600.0 / width
            # Storing PhotoImage in global variable to prevent it from being deleted once this function exits
            # since PhotoImage has a __del__ destructor
            scanned_image = PIL.ImageTk.PhotoImage(img.resize(size=(int(width * factor), int(height * factor))))
            frm.destroy()
            ttk.Label(root, image=scanned_image).pack(side="left", fill="both", expand=1)
        else:
            print("User clicked cancel")


logging.basicConfig(level=logging.DEBUG)
root = tkinter.Tk()
frm = ttk.Frame(root, padding=10)
frm.grid()
ttk.Button(frm, text="Scan", command=scan).grid(column=0, row=0)
root.mainloop()
'''
the camera dialog is opened, but I get an error:
`INFO:twain:attempting to load dll: twaindsm.dll
INFO:twain:Calling DAT_PARENT/MSG_OPENDSM
INFO:twain:DSM initialized
INFO:twain:starting source selection dialog
INFO:twain:Calling DAT_IDENTITY/MSG_USERSELECT
INFO:twain:user selected source with id 1
INFO:twain:opening data source with id 1
INFO:twain:Calling DAT_IDENTITY/MSG_OPENDS
INFO:twain:starting scan
INFO:twain:Calling DAT_USERINTERFACE/MSG_ENALEDS
INFO:twain:Calling DAT_IMAGENATIVEXFER
INFO:twain:Calling DAT_PENDINGXFERS/MSG_ENDXFER
INFO:twain:Calling DAT_USERINTERFACE/MSG_DISABLEDS
INFO:twain:closing data source with id 1
INFO:twain:Calling DAT_IDENTITY/MSG_CLOSEDS
INFO:twain:Calling DAT_PARENT/MSG_CLOSEDSM
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Documents\GitHub\Sample_scaner\Snaper\23.py", line 19, in scan
    (handle, remaining_count) = src.xfer_image_natively()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\site-packages\twain\__init__.py", line 831, in xfer_image_natively
    raise exceptions.DSTransferCancelled
twain.exceptions.DSTransferCancelled`

**Comment by denisenkom** [comment]
Try checking your scanner driver via Twacker, you can get it here https://github.com/twain/twain-toolkit

**Comment by denisenkom** [comment]
Also I added more logging, try using latest version from repository with sample code.  Then add log output here.

**Comment by ji-ze** [comment]
> Try checking your scanner driver via Twacker, you can get it here https://github.com/twain/twain-toolkit

It works via Twacker.
![image](https://github.com/denisenkom/pytwain/assets/44098973/7bef6d98-4100-4419-b39d-e10ce6175d33)

**Comment by ji-ze** [comment]
> Also I added more logging, try using latest version from repository with sample code. Then add log output here.

I got:
```
INFO:twain:Calling DAT_EVENT/MSG_PROCESSEVENT
DEBUG:twain:Calling TWAIN (<twain.lowlevel.structs.TW_IDENTITY object at 0x0000024B4BCC8D50>,1,2,1537)
DEBUG:twain:TWAIN returned: 4
DEBUG:twain:handling event result 4
INFO:twain:Calling DAT_EVENT/MSG_PROCESSEVENT
DEBUG:twain:Calling TWAIN (<twain.lowlevel.structs.TW_IDENTITY object at 0x0000024B4BCC8D50>,1,2,1537)
DEBUG:twain:TWAIN returned: 4
DEBUG:twain:handling event result 4
INFO:twain:transfer is ready
INFO:twain:got MSG_XFERREADY message
INFO:twain:Calling DAT_IMAGEINFO/MSG_GET
DEBUG:twain:Calling TWAIN (<twain.lowlevel.structs.TW_IDENTITY object at 0x0000024B4BCC8D50>,2,257,1)
DEBUG:twain:TWAIN returned: 0
INFO:twain:Calling DAT_IMAGENATIVEXFER
DEBUG:twain:Calling TWAIN (<twain.lowlevel.structs.TW_IDENTITY object at 0x0000024B4BCC8D50>,2,260,1)
DEBUG:twain:TWAIN returned: 6
INFO:twain:Calling DAT_PENDINGXFERS/MSG_ENDXFER
DEBUG:twain:Calling TWAIN (<twain.lowlevel.structs.TW_IDENTITY object at 0x0000024B4BCC8D50>,1,5,1793)
DEBUG:twain:TWAIN returned: 0
INFO:twain:Calling DAT_USERINTERFACE/MSG_DISABLEDS
DEBUG:twain:Calling TWAIN (<twain.lowlevel.structs.TW_IDENTITY object at 0x0000024B4BCC8D50>,1,9,1281)
<twain._Image object at 0x0000024B4BCE3090>
DEBUG:twain:TWAIN returned: 0
INFO:twain:closing data source with id 1
INFO:twain:Calling DAT_IDENTITY/MSG_CLOSEDS
DEBUG:twain:Calling TWAIN (None,1,3,1026)
DEBUG:twain:TWAIN returned: 0
INFO:twain:Calling DAT_PARENT/MSG_CLOSEDSM
DEBUG:twain:Calling TWAIN (None,1,4,770)
DEBUG:twain:TWAIN returned: 0
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\GitHub\Sample_scaner\Snaper\twain_scan_test.py", line 21, in <module>
    src.acquire_natively(after, show_ui=True)
  File "C:\ProgramData\miniconda3\Lib\site-packages\twain\__init__.py", line 942, in acquire_natively
    self._acquire(
  File "C:\ProgramData\miniconda3\Lib\site-packages\twain\__init__.py", line 647, in _acquire
    self._modal_loop(event_callback_lolevel)
  File "C:\ProgramData\miniconda3\Lib\site-packages\twain\__init__.py", line 615, in _modal_loop
    event_callback(event)
  File "C:\ProgramData\miniconda3\Lib\site-packages\twain\__init__.py", line 641, in event_callback_lolevel
    more = xfer_ready_callback()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\site-packages\twain\__init__.py", line 931, in xfer_ready_callback
    after(
  File "C:\Users\Administrator\Documents\GitHub\Sample_scaner\Snaper\twain_scan_test.py", line 8, in after
    twain.windows.dib_to_bm_file(i, 'Test001.bmp')
  File "C:\ProgramData\miniconda3\Lib\site-packages\twain\windows.py", line 68, in dib_to_bm_file
    size = GlobalSize(handle)
           ^^^^^^^^^^^^^^^^^^
ctypes.ArgumentError: argument 1: TypeError: wrong type
```

**Comment by denisenkom** [comment]
Looks like you have issue in this line:
```
twain.windows.dib_to_bm_file(i, 'Test001.bmp')
```
The variable `i` here contains instance of `_Image`, and you are passing it to `dib_to_bm_file` which expects a memory handle.  You should instead write:
```
i.save('Test001.bmp')
```

**Comment by ji-ze** [comment]
Thank you. It works!
