### ISSUE TITLE
twain.excSMLoadFileFailed: [WinError 193] %1 this is not a valid win32 application

### ISSUE THREAD

**Issue by yazilimci1** [denisenkom/pytwain#5]
I have 64 bit Windows and use 64 bit Python . I have installed this module and when I execute the application got this error . I need to ask you this error message means that pytwain does not support for 64 bit Windows  if so is there anyway to run pytwain on 64 bit Windows?

**Comment by denisenkom** [comment]
Try installing 64 bit TWAIN DSM: http://sourceforge.net/projects/twain-dsm/

**Comment by yazilimci1** [comment]
I downloaded file  and copy TWAINDSM.DLL into C:\Windows\SysWow64 . Then I test this code:
```import twain
sm = twain.SourceManager(0)
ss = sm.OpenSource()
ss.RequestAcquire(0,0)
rv = ss.XferImageNatively()
if rv:
    (handle, count) = rv
twain.DIBToBMFile(handle, 'image.bmp')
```
and it works . Opens a window  like :
![tara](https://cloud.githubusercontent.com/assets/6942147/12375478/f97c1748-bccc-11e5-947f-c24e9357a562.png)
. So why this is empty , the scanner will show in this window ?

**Comment by denisenkom** [comment]
64 bit twaindsm.dll should be copied to C:\Windows\System32
32 bit twaindsm.dll should be copied to C:\Windows\SysWow64
Yes this sounds misleading.

If it still wouldn't work then this means your scanner doesn't support 64 bit drivers. In this case you might want to try 32 bit python instead.

**Comment by yazilimci1** [comment]
I have installed Python 2.7 32 bit on Windows and installed pytwain but when I execute the above code , got this error 
Traceback (most recent call last):
  File "C:/Users/PB/PycharmProjects/Python2.7Deneme/TwainDeneme.py", line 4, in <module>
    sm = twain.SourceManager(0)
  File "C:\Python27\lib\site-packages\twain.py", line 2029, in __init__
    self._call(None, DG_CONTROL, DAT_PARENT, MSG_OPENDSM, byref(c_void_p(self._hwnd)))
  File "C:\Python27\lib\site-packages\twain.py", line 2090, in _call
    raise Exception('DG_CONTROL DAT_STATUS MSG_GET returned non success code, rv = %d' % rv)
Exception: DG_CONTROL DAT_STATUS MSG_GET returned non success code, rv = 1

**Comment by yazilimci1** [comment]
I have installed some of package about twain and suddenly the application works in 32 bit Python2.7 . But when running in 64 bit Python 3.4 my scanner drivers not show . Do you think it is like you said "scanner doesn't support 64 bit drivers"

**Comment by denisenkom** [comment]
> Do you think it is like you said "scanner doesn't support 64 bit drivers"
Yes, looks like it.  You might try searching for newer drivers on manufacturer's website.
